### ISSUE TITLE
Incorrect sequencing

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/python-p4-sending-get-requests#2]
### Canvas Link

https://learning.flatironschool.com/courses/6182/pages/sending-get-requests?module_item_id=480480

### Concern

In this paragraph it talks about learning about web scraping being a process they don't need to learn yet but the prior module for this phase is about web scraping:
"So, we've seen how to get the HTML code from a webpage. Although this is cool, in its current state, this isn't very useful information. There are actually tools designed specifically to take this raw HTML and turn it into organized data for us in a process known as scraping, but we don't need to learn that just yet. Plenty of data is already organized and made available to us separate from HTML code and we can retrieve it the same way we send a GET request to a website."

### Additional Context

It should be noted that the web scraping module is an optional module.

**Comment by pgill97** [comment]
Changed lesson to say `There are actually tools designed specifically to take this raw HTML and turn it into organized data for us in a process known as scraping, which we learned about in the previous optional module.  `
